In [569]:
import pandas as pd

In [625]:
alpertc = pd.read_csv("MenuKalorileri1.csv") #Büyük küçük harf duyarlı değil.
#veri ismini istediğiniz şey olarak kaydedebilirsiniz.
# Arama özelliğiyle değiştirilen özelliklere dikkat etmek gerek belgeyi okuyamayabilir.
# Csv doyasını direkt olarak pandas(pd) ile DataFrame olarak kaydediyor.Dosyada kolonlar ve rowlar bulunuyor.

In [641]:
alpertc.head() #Print'e ihtiyaç olamadan (Jupyter'e özel olabilir) görmeyi sağlıyor.
#alpertc.tail() ile parantez içine girdiğimiz sayı kadar veriyi sondan başlayarak gösterir

,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
1,Cheeseburger,300.0,110.0,12.0,6,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
3,McDouble,390.0,170.0,19.0,8,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Frappe Mocha (Medium),560.0,210.0,24.0,15,1.0,65.0,160.0,78.0,1.0,70.0,8.0,637.0
323,Frappe Mocha (Large),680.0,250.0,28.0,18,1.0,80.0,200.0,96.0,1.0,87.0,10.0,775.0
324,Strawberry Banana Smoothie (Large),330.0,10.0,1.0,0.5,0.0,5.0,55.0,77.0,4.0,70.0,3.0,397.5
325,Strawberry Banana Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,40.0,60.0,3.0,54.0,2.0,312.0
326,Strawberry Banana Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,35.0,49.0,2.0,44.0,2.0,252.0

In [627]:
alpertc[["Item"]] #Index kalır, istenilen column'u (kolonu) alır. DataFrame şeklinde.Satırları değil KOLONLARI ALIRIZ.
#Row=Satır , Column=Kolon(Sütun)

                                    Item
0                              Hamburger
1                           Cheeseburger
2                    Double Cheeseburger
3                               McDouble
4           Quarter Pounder® with Cheese
..                                   ...
325  Strawberry Banana Smoothie (Medium)
326   Strawberry Banana Smoothie (Small)
327          Wild Berry Smoothie (Large)
328         Wild Berry Smoothie (Medium)
329          Wild Berry Smoothie (Small)

[330 rows x 1 columns]

In [628]:
alpertc[["Item","Calories"]] #2 Tane istenilen kolon ',' ile ayrılarak aynı liste içinde yazılırsa o 2 kolonu alır
# istekkolonlar = ["Item","Calories"] yazıp dataframe[istekkolonlar] yazarsak aynı sonucu verir.
# istenilen bilgileri birden fazla kez yazmak gerekiyorsa pratiklik sağlayabilir

                                    Item  Calories
0                              Hamburger     250.0
1                           Cheeseburger     300.0
2                    Double Cheeseburger     440.0
3                               McDouble     390.0
4           Quarter Pounder® with Cheese     510.0
..                                   ...       ...
325  Strawberry Banana Smoothie (Medium)     260.0
326   Strawberry Banana Smoothie (Small)     210.0
327          Wild Berry Smoothie (Large)     320.0
328         Wild Berry Smoothie (Medium)     260.0
329          Wild Berry Smoothie (Small)     210.0

[330 rows x 2 columns]

In [629]:
isimkaloridatasi = alpertc[["Item","Calories"]] #Yeni isimkaloridatasi yeni dataframedir.
#2 tane kolonu alıp yeni dataframe oluşturduk diğer yaptığımız işlemlerde kalıcı kayıt olmadığı için sadece geçici olarak
#alpertc ve kolonları o anlığına kaydetti ana dataframe(origin) sabit kaldı
#Yazdırarak doğruluğunu kontrol edebilirsin

In [630]:
type(alpertc["Item"]) # Tek bir tane [] koyarsak alpertc 'DataFrame' değil de 'Series' oluyor
#Seriler yalnızca 1 tane data column'u içerebiliyorken dataframe'de böyle bir kısıtlama yok (Class farkı)
#Bir seri oluştururken; 
#1) pd.Series(Liste) kullanırsak oluştururuz ama 1. kolonu otomatik olarak 0'dan başlayarak sayılarla index alır
#2) pd.Series(liste,liste) kullanırsak index ve data'yı 2 liste kullanarak girebiliriz.
#       İlk girilen liste data, ikinci girilen liste ise indexi belirtir.
#3) pd.Series(dictionary) kullanırsak sözlük class'ı zaten 2 alpertc içerdiği için key'leri index olarak karşılık değerleri de
# values olarak atar.
# Not= pd.Series(data=liste2,index=liste1) Şeklinde belirlersek data ve indexleri manuel olarak girebiliriz.
#Oluşturulanların hepsi Pandas kütüphanesinin Series class'ına mensuptur.

pandas.core.series.Series

In [631]:
alpertc[["Item"]] #Bu bir DataFrame
alpertc["Item"] #Bu bir Seri

0                                Hamburger
1                             Cheeseburger
2                      Double Cheeseburger
3                                 McDouble
4             Quarter Pounder® with Cheese
                      ...
325    Strawberry Banana Smoothie (Medium)
326     Strawberry Banana Smoothie (Small)
327            Wild Berry Smoothie (Large)
328           Wild Berry Smoothie (Medium)
329            Wild Berry Smoothie (Small)
Name: Item, Length: 330, dtype: object

In [632]:
alpertc["Item"][0] #alpertc["Item"] seri olduğu için ikinci koyduğumuz [] ile indexi girer ve değerini çağrırız.
#Normalde SeriClassı[Index] ile alpertcyi çağrırız ama normal alpertc dataframe'ken alpertc["Item"] seri olduğu için kullanımı
#Series'e çevirdikten sonra İndex girmiş oluruz.

'Hamburger'

In [633]:
#Seriler birbiri ile toplanabilir.
#Serilerdeki veriler int(sayısal) veriler değilse toplanmaz ve NaN olarak geçer. NaN boş veridir ve genelde istenmez.

In [634]:
#DataFrame'e geri dönecek olursak
# alpertc DataFrame şeklindeydi yeni bir dataframe oluşturalım.
# pd.DataFrame() bize dataframe oluşturmayı sağlar. 
# pd.DataFrame(data,index=[],columns=[]) data numpy ile oluşturulabilir.

In [635]:
yenialpertc = pd.DataFrame(alpertc,index=[0,123,2,8,4]) #İle sadece 5 index'i dataframe şeklinde alabiliriz sayısı fark etmez.
#pd.DataFrame(data,index=[]) İle istediğimiz kadar spesifik olarak seçtiğimiz rowları(indexleri) alarak
#0,123,2,8,4 indexlileri alır ve yeni dataframe oluştururuz kolonları spesifik belirtmediğimiz için tamamını alır.
#DİKKAT = DataFrame'deki sıralama belirlediğimiz şekilde gelir 0,123,2,8,4 şeklinde belirlenecek.

In [636]:
yenialpertc

,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
123,Chocolate McCafé® Shake (16 fl oz cup),720.0,180.0,20.0,12,1.0,60.0,300.0,119.0,1.0,98.0,15.0,815.0
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
8,Big N’ Tasty® with Cheese,510.0,250.0,28.0,11,1.5,85.0,960.0,38.0,3.0,8.0,27.0,502.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0

In [637]:
yenialpertc = pd.DataFrame(alpertc,columns=["Item","Naber","Calories"]) #İle İndex belirtmediğimiz için indexlerin hepsini alır.
#Bahsettiğimiz kolon olmadığı için yeni kolon oluşturur ama değerleri olmadığı için NaN şeklinde belirir.
#Bahsedilen kolonlar varsa Onları alır ve yine belirttiğimiz sıraya göre (soldan sağa) oluşturur.

In [638]:
yenialpertc

                                    Item  Naber  Calories
0                              Hamburger    NaN     250.0
1                           Cheeseburger    NaN     300.0
2                    Double Cheeseburger    NaN     440.0
3                               McDouble    NaN     390.0
4           Quarter Pounder® with Cheese    NaN     510.0
..                                   ...    ...       ...
325  Strawberry Banana Smoothie (Medium)    NaN     260.0
326   Strawberry Banana Smoothie (Small)    NaN     210.0
327          Wild Berry Smoothie (Large)    NaN     320.0
328         Wild Berry Smoothie (Medium)    NaN     260.0
329          Wild Berry Smoothie (Small)    NaN     210.0

[330 rows x 3 columns]

In [639]:
yenialpertc = pd.DataFrame(alpertc,index=[0,9,99],columns=["Item","Calories"]) #Bu oluşturduğumuz DataFrame ile
# 1,10,100. sıradaki alpertclerin item'larını kalorilerini aldık.Aslında Türkçe olarak 1,10,100. sıradaki menülerin isim ve kalorilerini aldık.

In [640]:
yenialpertc

                         Item  Calories
0                   Hamburger     250.0
9        Angus Bacon & Cheese     790.0
99  Bacon, Egg & Cheese Bagel     560.0

In [586]:
#Geri ilk dataframemiz olan alpertc'ye dönersek:
alpertc

,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
1,Cheeseburger,300.0,110.0,12.0,6,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
3,McDouble,390.0,170.0,19.0,8,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Strawberry Banana Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,40.0,60.0,3.0,54.0,2.0,312.0
326,Strawberry Banana Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,35.0,49.0,2.0,44.0,2.0,252.0
327,Wild Berry Smoothie (Large),320.0,10.0,1.0,0.5,0.0,5.0,45.0,75.0,4.0,69.0,3.0,386.5
328,Wild Berry Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,35.0,60.0,4.0,55.0,3.0,312.0
329,Wild Berry Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,30.0,48.0,3.0,44.0,2.0,252.0

In [587]:
#Bu DataFrame'den satır verisini çekmek istersek DataFrame.loc[index] gireriz.
#Bu girdiğimiz index ile indexini girdiğimiz satırın(row) bilgilerini Series halinde alırız.
alpertc.loc[0] #Bu yazdığımız 0 İndex'in kendisidir. Sayı değil de İndexler isim olsaydı 0 yerine o ismi girmemiz gerekirdi.

Item                     Hamburger
Calories                     250.0
Calories from\nFat            80.0
Total Fat\n(g)                 9.0
Saturated Fat\n(g)             3.5
Trans Fat\n(g)                 0.5
Cholesterol\n(mg)             25.0
Sodium \n(mg)                520.0
Carbs\n(g)                    31.0
Fiber\n(g)                     2.0
Sugars\n(g)                    6.0
Protein\n(g)                  12.0
Weight Watchers\nPnts        247.5
Name: 0, dtype: object

In [588]:
# 0 indexinin sütunları(column) indexe dönüşür. Girilen bilgileri yani satırdakileri(row)'ları ise values(değerleri) olur.
alpertc.iloc[0] #İse aynı şekilde yapar fakat indexlerin isim olmadığı durumlarda 0'dan başlayarak giden bir şekilde indexleri
#sayı ile seçmemizi sağlar.

Item                     Hamburger
Calories                     250.0
Calories from\nFat            80.0
Total Fat\n(g)                 9.0
Saturated Fat\n(g)             3.5
Trans Fat\n(g)                 0.5
Cholesterol\n(mg)             25.0
Sodium \n(mg)                520.0
Carbs\n(g)                    31.0
Fiber\n(g)                     2.0
Sugars\n(g)                    6.0
Protein\n(g)                  12.0
Weight Watchers\nPnts        247.5
Name: 0, dtype: object

In [589]:
alpertc[["YeniKolon"]]=0 #Olmayan bir kolon ismi koyarak yeni bir kolon ekleyip bütün rowlar için bütün değeri 0 olarak atadık.

In [590]:
#Bu istemediğimiz bir kolon olduğu için kolonu düşürelim. axis=1 demek zorundayız.
#axis=1 demezsek satırı düşürür.
#NOT=Satırın indexini girip satırı düşürürüz.
#axis'ten sonra ',' koyup inplace=True yaparsak alpertcnin origin'inde yani kaynağında da değişiklik yapar.
alpertc.drop("YeniKolon",axis=1,inplace=True)

In [591]:
#Veri Kontrolü Operator İşlemi Kalori sütununun 100'den büyük değerlerini True olmayanları False olarak alır.
alpertc[["Calories"]] >100

     Calories
0        True
1        True
2        True
3        True
4        True
..        ...
325      True
326      True
327      True
328      True
329      True

[330 rows x 1 columns]

In [592]:
alpertc[alpertc["Calories"]>100] #Kullanarak Veri'de Kalori Sütununda 100'den büyük olan satırları alır.

,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
1,Cheeseburger,300.0,110.0,12.0,6,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
3,McDouble,390.0,170.0,19.0,8,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Strawberry Banana Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,40.0,60.0,3.0,54.0,2.0,312.0
326,Strawberry Banana Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,35.0,49.0,2.0,44.0,2.0,252.0
327,Wild Berry Smoothie (Large),320.0,10.0,1.0,0.5,0.0,5.0,45.0,75.0,4.0,69.0,3.0,386.5
328,Wild Berry Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,35.0,60.0,4.0,55.0,3.0,312.0
329,Wild Berry Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,30.0,48.0,3.0,44.0,2.0,252.0

In [593]:
# Verilerimizin hepsi Str olmadığı için (Itemlar) alpertc >100 işlemini yapamayız. Hata verir.
#2 önceki örnekte olan true/false sonuçlarını verir eğer string veri yoksa.
#----
#Şimdi dataframe'de İndexleri kendimiz belirleyelim

In [594]:
alpertc.set_index("Item",inplace=True) #Bu şekilde "Item" isimli kolonumuzu İndex'imiz yaptık.
#Inplace=True diyerek bunu asılında da değiştirmiş olduk.

In [595]:
alpertc.reset_index(inplace=True) #İle indexleri 0'dan başlayacak şekilde sıfırlamış oluruz.inplace=True yapmazsak alpertc normal kalırdı.
#DİKKAT = 2 Kere kullanılırsa 1 tane daha 0,1 numaralı index kolonu ekler.!!!

In [596]:
alpertc #alpertc.index.names = [] liste ile indexlerin isimlerini verdiğimiz listeyle kendimiz belirlyebebiliriz.

,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
1,Cheeseburger,300.0,110.0,12.0,6,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
3,McDouble,390.0,170.0,19.0,8,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Strawberry Banana Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,40.0,60.0,3.0,54.0,2.0,312.0
326,Strawberry Banana Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,35.0,49.0,2.0,44.0,2.0,252.0
327,Wild Berry Smoothie (Large),320.0,10.0,1.0,0.5,0.0,5.0,45.0,75.0,4.0,69.0,3.0,386.5
328,Wild Berry Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,35.0,60.0,4.0,55.0,3.0,312.0
329,Wild Berry Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,30.0,48.0,3.0,44.0,2.0,252.0

In [597]:
alpertc.rename(columns={"Item":"Isimler","Calories":"Kaloriler"},inplace=True) #KOLON İSMİ DEĞİŞTİRME
#alpertc.rename(columns={"Kolonİsmi":"Yeniİsim"},inplace=) İle Kolonun ismini değiştiririz.
#Fazladan not alpertc = alpertc.reindex(sorted(alpertc.columns), axis=1) ile alfabetik olarak kolonları sıralamış hali alınır.
#alpertc.columns.values[SAYI] = 'Yeniİsim' İle Kolonun Sırasını baz alarak kolon ismini değiştirebiliriz.
alpertc

,Isimler,Kaloriler,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
1,Cheeseburger,300.0,110.0,12.0,6,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
3,McDouble,390.0,170.0,19.0,8,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Strawberry Banana Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,40.0,60.0,3.0,54.0,2.0,312.0
326,Strawberry Banana Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,35.0,49.0,2.0,44.0,2.0,252.0
327,Wild Berry Smoothie (Large),320.0,10.0,1.0,0.5,0.0,5.0,45.0,75.0,4.0,69.0,3.0,386.5
328,Wild Berry Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,35.0,60.0,4.0,55.0,3.0,312.0
329,Wild Berry Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,30.0,48.0,3.0,44.0,2.0,252.0

In [598]:
alpertc.columns.values[2:4] = "Yagdan Gelen Kalori","Toplam Yag" #2'den 4 e kadar sırayla değiştirir.
alpertc.columns.values[4:13] = "Doymus Yag","Trans Yag","Kolestrol","Sodyum","Karbonhidrat","Fiber","Seker","Protein","WeightWatcher Puani"
alpertc

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Trans Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
0,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5
1,Cheeseburger,300.0,110.0,12.0,6,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
3,McDouble,390.0,170.0,19.0,8,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Strawberry Banana Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,40.0,60.0,3.0,54.0,2.0,312.0
326,Strawberry Banana Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,35.0,49.0,2.0,44.0,2.0,252.0
327,Wild Berry Smoothie (Large),320.0,10.0,1.0,0.5,0.0,5.0,45.0,75.0,4.0,69.0,3.0,386.5
328,Wild Berry Smoothie (Medium),260.0,5.0,1.0,0,0.0,5.0,35.0,60.0,4.0,55.0,3.0,312.0
329,Wild Berry Smoothie (Small),210.0,5.0,0.5,0,0.0,5.0,30.0,48.0,3.0,44.0,2.0,252.0

In [599]:
#Eksik Veri Düşürme alpertc.dropna() ile en az 1 NaN değeri olan SATIRLARIN tamamını düşürürüz.
#alpertc.dropna(axis=1) ile en az 1 NaN değeri olan SÜTUNLARIN tamamını düşürürüz.
#alpertc.dropna(axis=1,thresh=X) yaparsak X veya daha fazla NaN'a sahip SÜTUNLARI düşürür.

In [600]:
#En BAŞINDA aslında null yani belirsiz değerimiz var mı kontrol etmemiz lazım
alpertc.isnull() #Tek tek her satır ve sütunda eksik alpertc var mı kontrol eder yoksa False varsa True der.

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Trans Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,False,False,False,False,False,False,False,False,False,False,False,False,False
326,False,False,False,False,False,False,False,False,False,False,False,False,False
327,False,False,False,False,False,False,False,False,False,False,False,False,False
328,False,False,False,False,False,False,False,False,False,False,False,False,False
329,False,False,False,False,False,False,False,False,False,False,False,False,False

In [601]:
alpertc.isnull().sum() #Dersek Hangi Sütunda kaç tane null değer olduğunu bize bildirir.

Isimler                0
Kaloriler              2
Yagdan Gelen Kalori    5
Toplam Yag             2
Doymus Yag             2
Trans Yag              2
Kolestrol              2
Sodyum                 2
Karbonhidrat           2
Fiber                  2
Seker                  2
Protein                2
WeightWatcher Puani    5
dtype: int64

In [602]:
alpertc[alpertc.isna().any(axis=1)] #Bunlar hangi değerler görmek istersek aşağıdakini yaparız.Rowları bize gösterir.

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Trans Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
64,Salad Dressings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Hamburger Happy Meal,475.0,NaN,16.0,5.5 g,0.0,40.0,690.0,62.0,2.0,20.0,22.0,NaN
103,4 Piece Chicken McNuggets Happy Meal,395.0,NaN,17.0,3.5,0.0,35.0,510.0,41.0,1.0,14.0,19.0,NaN
104,6 Piece Chicken McNuggets® Happy Meal,475.0,NaN,22.0,4.5,0.0,50.0,680.0,46.0,2.0,14.0,24.0,NaN
259,McCafe Coffees – Whole Milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [603]:
#Burada az değer olduğu için bu değerleri düşürebiliriz. alpertc.dropna() yaparız.Rowların hepsini düşürür.
alpertc.dropna(inplace=True) #Kayıtlı kalsın ve sorun çıkarmasın diye inplace=True yaptık.
#Artık hiçbir na değerine sahip değiliz yani eksik değerimiz yok.
#Not= Eksik değerleri elimizdeki veriye göre kayıp olmaması için genel değerlerin ortalamaları ile doldurabiliriz.
#alpertc.fillna() Komudu ile yaparız.!!

In [604]:
#GRUPLAMA
#İstediğimiz sütunlardaki aynı olan değerler için gruplama yapabiliriz.
#alpertc.groupby("Sütun İsmi")
######gruplandirilmisalpertc = alpertc.groupby("Trans Yag")
#Trans Yag ayrı yazıldığı için hata verir 
#bunu düzeltmek için alpertc.columns = alpertc.columns.str.strip() yaparız.
alpertc.columns = alpertc.columns.str.strip()

In [605]:
gruplandirilmisalpertc = alpertc.groupby("Trans Yag")

In [606]:
gruplandirilmisalpertc.count() #Count İle Trans Yağ'a göre aynı değerleri alan sütunlar gruplandırılır.
#Bakılana göre Trans yağ içermeyen 269 ürün bulunuyor
#En fazla trans yağ içeren ürünse 1 tane olup 2.5 gram içermekte.

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
Trans Yag,,,,,,,,,,,,
0.0,269,269,269,269,269,269,269,269,269,269,269,269
0.5,13,13,13,13,13,13,13,13,13,13,13,13
1.0,24,24,24,24,24,24,24,24,24,24,24,24
1.5,11,11,11,11,11,11,11,11,11,11,11,11
2.0,7,7,7,7,7,7,7,7,7,7,7,7
2.5,1,1,1,1,1,1,1,1,1,1,1,1

In [607]:
#Mean Fonksiyonu İle Ortalamalara Genel Bakış
alpertc.mean() #İle SADECE SAYI bulunan sütunları toplayarak ortalamalarını alır.
#Ürünlerin ortalama kalorileri ve diğer özellikleri aşağıdaki gibiymiş

C:\Users\atc45\AppData\Local\Temp\ipykernel_7996\1866183527.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  alpertc.mean() #İle SADECE SAYI bulunan sütunları toplayarak ortalamalarını alır.

Kaloriler              283.107692
Yagdan Gelen Kalori     88.800000
Toplam Yag               9.910769
Trans Yag                0.195385
Kolestrol               40.215385
Sodyum                 335.800000
Karbonhidrat            39.920000
Fiber                    0.873846
Seker                   28.215385
Protein                  9.320000
WeightWatcher Puani    306.426154
dtype: float64

In [608]:
gruplandirilmisalpertc.mean() #gruplandırılmış dataframelerin de ortalamalarını alabiliriz.

C:\Users\atc45\AppData\Local\Temp\ipykernel_7996\1242482678.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  gruplandirilmisalpertc.mean() #gruplandırılmış dataframelerin de ortalamalarını alabiliriz.

,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
Trans Yag,,,,,,,,,,
0.0,219.070632,65.724907,7.345725,31.412639,285.278810,31.825279,0.776952,22.501859,7.364312,237.163569
0.5,416.153846,142.307692,15.923077,81.538462,427.692308,55.230769,1.000000,38.615385,13.000000,449.807692
1.0,578.750000,178.750000,19.916667,70.208333,391.041667,85.208333,0.916667,66.500000,14.375000,642.083333
1.5,595.454545,230.000000,25.636364,78.181818,716.363636,70.090909,1.727273,43.818182,21.363636,630.090909
2.0,927.142857,304.285714,33.714286,122.857143,1170.000000,119.857143,2.571429,75.428571,35.857143,983.285714
2.5,740.000000,380.000000,42.000000,155.000000,1380.000000,40.000000,3.000000,9.000000,48.000000,720.000000

In [609]:
alpertc.max() #MAX fonksiyonu ile maximum sayı değerine sahip içerik gösterilir.

Isimler                Wild Berry Smoothie (Small)
Kaloriler                                   1160.0
Yagdan Gelen Kalori                          540.0
Toplam Yag                                    60.0
Doymus Yag                                       9
Trans Yag                                      2.5
Kolestrol                                    575.0
Sodyum                                      2260.0
Karbonhidrat                                 203.0
Fiber                                          7.0
Seker                                        168.0
Protein                                       48.0
WeightWatcher Puani                         1317.0
dtype: object

In [610]:
alpertc.min() #MİN ile minimum değerlere sahip içerik gösterilir.

Isimler                 Quarter Pounder® with Cheese
Kaloriler                                        0.0
Yagdan Gelen Kalori                              0.0
Toplam Yag                                       0.0
Doymus Yag                                         0
Trans Yag                                        0.0
Kolestrol                                        0.0
Sodyum                                           0.0
Karbonhidrat                                     0.0
Fiber                                            0.0
Seker                                            0.0
Protein                                          0.0
WeightWatcher Puani                              0.0
dtype: object

In [611]:
gruplandirilmisalpertc.max() #Gruplara Göre Verilerin Maximumunu alır.

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
Trans Yag,,,,,,,,,,,,
0.0,Wild Berry Smoothie (Small),1150.0,540.0,60.0,9,575.0,2260.0,116.0,7.0,94.0,38.0,1151.0
0.5,Vanilla Triple Thick® Shake (12 fl oz cup),610.0,320.0,36.0,9,410.0,1390.0,76.0,3.0,63.0,27.0,601.0
1.0,Vanilla Triple Thick® Shake (21 fl oz cup),770.0,300.0,33.0,9,300.0,1580.0,134.0,4.0,111.0,33.0,874.0
1.5,Vanilla McCafé® Shake (22 fl oz cup),880.0,260.0,29.0,8,90.0,1190.0,147.0,3.0,124.0,29.0,998.0
2.0,Vanilla Triple Thick Shake® (32 fl oz cup),1160.0,360.0,40.0,18,145.0,2070.0,203.0,4.0,168.0,45.0,1317.0
2.5,Double Quarter Pounder® with Cheese,740.0,380.0,42.0,19,155.0,1380.0,40.0,3.0,9.0,48.0,720.0

In [612]:
gruplandirilmisalpertc.min()

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
Trans Yag,,,,,,,,,,,,
0.0,1% Low Fat Chocolate Milk Jug,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.5,"Bacon, Egg & Cheese Bagel",250.0,80.0,9.0,10,25.0,130.0,31.0,0.0,4.0,9.0,247.5
1.0,Angus Bacon & Cheese Snack Wrap,330.0,120.0,13.0,10,45.0,130.0,26.0,0.0,3.0,6.0,325.0
1.5,Quarter Pounder® with Cheese,410.0,210.0,23.0,10,70.0,200.0,27.0,0.0,2.0,10.0,403.0
2.0,Angus Bacon & Cheese,750.0,240.0,26.0,16,100.0,350.0,59.0,0.0,8.0,25.0,736.0
2.5,Double Quarter Pounder® with Cheese,740.0,380.0,42.0,19,155.0,1380.0,40.0,3.0,9.0,48.0,720.0

In [613]:
alpertc.describe() #Describe İle de Genel Açıklamalari Görebiliriz.

,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Trans Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
count,325.000000,325.000000,325.000000,325.000000,325.000000,325.000000,325.000000,325.000000,325.000000,325.000000,325.000000
mean,283.107692,88.800000,9.910769,0.195385,40.215385,335.800000,39.920000,0.873846,28.215385,9.320000,306.426154
std,219.010198,99.605425,11.065031,0.477400,79.638166,437.260841,31.092947,1.448528,28.681678,9.379305,232.483311
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,140.000000,0.000000,0.000000,0.000000,5.000000,85.000000,20.000000,0.000000,6.000000,2.000000,153.500000
50%,230.000000,60.000000,6.000000,0.000000,15.000000,140.000000,36.000000,0.000000,18.000000,7.000000,267.000000
75%,380.000000,150.000000,16.000000,0.000000,40.000000,330.000000,49.000000,1.000000,43.000000,12.000000,395.000000
max,1160.000000,540.000000,60.000000,2.500000,575.000000,2260.000000,203.000000,7.000000,168.000000,48.000000,1317.000000

In [614]:
gruplandirilmisalpertc.describe()

          Kaloriler                                                       \
              count        mean         std    min    25%    50%     75%
Trans Yag
0.0           269.0  219.070632  160.420595    0.0  110.0  190.0   290.0
0.5            13.0  416.153846   94.915617  250.0  380.0  420.0   440.0
1.0            24.0  578.750000  127.221563  330.0  517.5  575.0   687.5
1.5            11.0  595.454545  183.049919  410.0  450.0  510.0   755.0
2.0             7.0  927.142857  188.034951  750.0  780.0  800.0  1110.0
2.5             1.0  740.000000         NaN  740.0  740.0  740.0   740.0

                  Yagdan Gelen Kalori              ... Protein        \
              max               count        mean  ...     75%   max
Trans Yag                                          ...
0.0        1150.0               269.0   65.724907  ...     9.0  38.0
0.5         610.0                13.0  142.307692  ...    13.0  27.0
1.0         770.0                24.0  178.750000  ...    17.0  33.0
1.5         880.0                11.0  230.000000  ...    25.0  29.0
2.0        1160.0                 7.0  304.285714  ...    44.5  45.0
2.5         740.0                 1.0  380.000000  ...    48.0  48.0

          WeightWatcher Puani                                               \
                        count        mean         std    min    25%    50%
Trans Yag
0.0                     269.0  237.163569  161.544473    0.0  126.5  225.0
0.5                      13.0  449.807692   95.764368  247.5  424.0  471.0
1.0                      24.0  642.083333  158.716843  325.0  581.5  647.0
1.5                      11.0  630.090909  240.426061  403.0  442.5  502.0
2.0                       7.0  983.285714  276.361306  736.0  763.0  789.0
2.5                       1.0  720.000000         NaN  720.0  720.0  720.0


               75%     max
Trans Yag
0.0         321.50  1151.0
0.5         499.00   601.0
1.0         783.25   874.0
1.5         853.00   998.0
2.0        1257.50  1317.0
2.5         720.00   720.0

[6 rows x 80 columns]

In [615]:
alpertc.loc[alpertc['Protein'] == 48] #Belirli Sütunun belirli Değerinden yola çıkarak Row'u çekme

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Trans Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
5,Double Quarter Pounder® with Cheese,740.0,380.0,42.0,19,2.5,155.0,1380.0,40.0,3.0,9.0,48.0,720.0

In [616]:
alpertc.loc[(alpertc['Protein'] >= 3) & (alpertc['Kaloriler'] <= 155)] #Proteini 3 ten büyük VE kalorisi 155 ten küçük değerli olanları alır.

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Trans Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
54,Premium Southwest Salad (without chicken),140.0,40.0,4.5,2,0.0,10.0,150.0,20.0,6.0,6.0,6.0,142.0
57,Premium Bacon Ranch Salad (without chicken),140.0,70.0,7.0,3.5,0.0,25.0,300.0,10.0,3.0,4.0,9.0,138.5
60,Premium Caesar Salad (without chicken),90.0,35.0,4.0,2.5,0.0,10.0,180.0,9.0,3.0,4.0,7.0,89.5
107,Vanilla Reduced Fat Ice Cream Cone,150.0,35.0,3.5,2,0.0,15.0,60.0,24.0,0.0,18.0,4.0,166.0
145,1% Low Fat Milk Jug,100.0,20.0,2.5,1.5,0.0,10.0,125.0,12.0,0.0,12.0,8.0,105.5
201,Nonfat Cappuccino (Small),60.0,0.0,0.0,0,0.0,5.0,85.0,9.0,0.0,9.0,6.0,63.0
202,Nonfat Cappuccino (Medium),80.0,0.0,0.0,0,0.0,5.0,110.0,12.0,0.0,12.0,8.0,84.0
203,Nonfat Cappuccino (Large),90.0,0.0,0.0,0,0.0,5.0,130.0,13.0,0.0,13.0,9.0,94.0
204,Nonfat Latte (Small),90.0,0.0,0.0,0,0.0,5.0,115.0,13.0,0.0,13.0,9.0,94.0
205,Nonfat Latte (Medium),110.0,0.0,0.0,0,0.0,5.0,140.0,15.0,0.0,15.0,10.0,115.0
206,Nonfat Latte (Large),120.0,0.0,0.0,0,0.0,5.0,160.0,18.0,0.0,18.0,12.0,126.0
207,Nonfat Caramel Cappuccino (Small),150.0,0.0,0.0,0,0.0,5.0,120.0,33.0,0.0,32.0,5.0,177.0
213,Nonfat Hazelnut Cappuccino (Small),150.0,0.0,0.0,0,0.0,5.0,70.0,34.0,0.0,34.0,5.0,179.0
219,Nonfat Vanilla Cappuccino (Small),150.0,0.0,0.0,0,0.0,5.0,70.0,34.0,0.0,34.0,5.0,179.0
225,Nonfat Cappuccino with Sugar Free Vanilla Syru...,50.0,0.0,0.0,0,0.0,5.0,100.0,15.0,0.0,8.0,5.0,53.0
226,Nonfat Cappuccino with Sugar Free Vanilla Syru...,70.0,0.0,0.0,0,0.0,5.0,130.0,19.0,0.0,10.0,7.0,73.0
227,Nonfat Cappuccino with Sugar Free Vanilla Syru...,80.0,0.0,0.0,0,0.0,5.0,150.0,22.0,0.0,11.0,8.0,83.0
228,Nonfat Latte with Sugar Free Vanilla Syrup (Sm...,80.0,0.0,0.0,0,0.0,5.0,130.0,18.0,0.0,11.0,7.0,84.0
229,Nonfat Latte with Sugar Free Vanilla Syrup (Me...,90.0,0.0,0.0,0,0.0,5.0,160.0,22.0,0.0,13.0,9.0,94.0
230,Nonfat Latte with Sugar Free Vanilla Syrup (La...,110.0,0.0,0.0,0,0.0,5.0,190.0,27.0,0.0,15.0,11.0,114.0
237,Iced Nonfat Latte (Small),50.0,0.0,0.0,0,0.0,5.0,70.0,7.0,0.0,7.0,5.0,52.0
238,Iced Nonfat Latte (Medium),60.0,0.0,0.0,0,0.0,5.0,90.0,9.0,0.0,9.0,6.0,63.0
239,Iced Nonfat Latte (Large),70.0,0.0,0.0,0,0.0,5.0,105.0,11.0,0.0,11.0,7.0,74.0
240,Iced Nonfat Caramel Latte (Small),140.0,0.0,0.0,0,0.0,0.0,105.0,30.0,0.0,30.0,3.0,167.0
241,Iced Nonfat Caramel Latte (Medium),150.0,0.0,0.0,0,0.0,5.0,120.0,32.0,0.0,32.0,5.0,177.0
243,Iced Nonfat Hazelnut Latte (Small),140.0,0.0,0.0,0,0.0,0.0,50.0,32.0,0.0,32.0,3.0,169.0
244,Iced Nonfat Hazelnut Latte (Medium),150.0,0.0,0.0,0,0.0,5.0,70.0,33.0,0.0,33.0,5.0,178.0
246,Iced Nonfat Vanilla Latte (Small),140.0,0.0,0.0,0,0.0,0.0,50.0,31.0,0.0,31.0,3.0,168.0
247,Iced Nonfat Vanilla Latte (Medium),150.0,0.0,0.0,0,0.0,5.0,70.0,33.0,0.0,33.0,5.0,178.0
249,Iced Nonfat Latte with Sugar Free Vanilla Syru...,40.0,0.0,0.0,0,0.0,0.0,85.0,13.0,0.0,5.0,4.0,41.0
250,Iced Nonfat Latte with Sugar Free Vanilla Syru...,50.0,0.0,0.0,0,0.0,5.0,100.0,14.0,0.0,6.0,5.0,51.0
251,Iced Nonfat Latte with Sugar Free Vanilla Syru...,60.0,0.0,0.0,0,0.0,5.0,130.0,19.0,0.0,8.0,6.0,62.0
260,Cappuccino (Small),120.0,60.0,7.0,4,0.0,20.0,85.0,9.0,0.0,9.0,6.0,127.0
261,Cappuccino (Medium),140.0,70.0,8.0,4.5,0.0,25.0,105.0,11.0,0.0,11.0,8.0,147.5
263,Latte (Small),150.0,70.0,8.0,4.5,0.0,25.0,105.0,11.0,0.0,11.0,8.0,157.5
284,Cappuccino with Sugar Free Vanilla Syrup (Small),100.0,50.0,5.0,3,0.0,15.0,105.0,15.0,0.0,7.0,5.0,105.0
285,Cappuccino with Sugar Free Vanilla Syrup (Medium),120.0,60.0,6.0,3.5,0.0,20.0,130.0,18.0,0.0,9.0,6.0,126.5
286,Cappuccino with Sugar Free Vanilla Syrup (Large),150.0,70.0,8.0,4.5,0.0,25.0,160.0,22.0,0.0,11.0,8.0,157.5
287,Latte with Sugar Free Vanilla Syrup (Small),130.0,60.0,7.0,4,0.0,20.0,125.0,17.0,0.0,10.0,7.0,137.0
296,Iced Latte (Small),80.0,40.0,4.5,2.5,0.0,15.0,65.0,6.0,0.0,6.0,4.0,84.5
297,Iced Latte (Medium),100.0,50.0,6.0,3.5,0.0,15.0,80.0,8.0,0.0,8.0,6.0,105.5
298,Iced Latte (Large),140.0,70.0,8.0,4.5,0.0,25.0,105.0,10.0,0.0,10.0,7.0,147.5
308,Iced Latte with Sugar Free Vanilla Syrup (Small),60.0,30.0,3.0,2,0.0,10.0,80.0,12.0,0.0,4.0,3.0,63.0
309,Iced Latte with Sugar Free Vanilla Syrup (Medium),90.0,40.0,5.0,3,0.0,15.0,105.0,14.0,0.0,6.0,5.0,94.0
310,Iced Latte with Sugar Free Vanilla Syrup (Large),110.0,50.0,6.0,3.5,0.0,15.0,130.0,19.0,0.0,8.0,6.0,115.5

In [617]:
alpertc.loc[(alpertc['Trans Yag'] > 1) & (alpertc["Kaloriler"] <=600)]

,Isimler,Kaloriler,Yagdan Gelen Kalori,Toplam Yag,Doymus Yag,Trans Yag,Kolestrol,Sodyum,Karbonhidrat,Fiber,Seker,Protein,WeightWatcher Puani
2,Double Cheeseburger,440.0,210.0,23.0,11,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0
4,Quarter Pounder® with Cheese,510.0,230.0,26.0,12,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0
6,Big Mac®,540.0,260.0,29.0,10,1.5,75.0,1040.0,45.0,3.0,9.0,25.0,534.0
7,Big N’ Tasty®,460.0,220.0,24.0,8,1.5,70.0,720.0,37.0,3.0,8.0,24.0,452.0
8,Big N’ Tasty® with Cheese,510.0,250.0,28.0,11,1.5,85.0,960.0,38.0,3.0,8.0,27.0,502.0
31,Angus Deluxe Snack Wrap,410.0,220.0,25.0,10,1.5,75.0,990.0,27.0,2.0,3.0,20.0,403.0
32,Angus Mushroom & Swiss Snack Wrap,430.0,230.0,26.0,10,1.5,75.0,730.0,27.0,2.0,2.0,22.0,420.0

In [618]:
# alpertc.loc[alpertc['Isimler'].isin(['str','str'])]
#isin string değerlerde (sayılamayanlarda) kullanılır.

In [619]:
alpertc["Kaloriler"].unique() #Belirtilen kolonadan sadece 1 kere değerleri alır.

array([ 250.,  300.,  440.,  390.,  510.,  740.,  540.,  460.,  790.,
        750.,  770.,  380.,  360.,  500.,  620.,  400.,  340.,  270.,
        330.,  260.,  800.,  410.,  430.,  230.,   15.,    0.,  190.,
        280.,  470.,   50.,   60.,  660.,  170.,  320.,  140.,  370.,
        220.,   90.,   20.,  210.,  100.,   40.,  450.,  160.,  420.,
        480.,  570.,  560., 1090., 1150.,  610.,  350.,  520.,  180.,
        150.,   35.,  290.,   70.,   45.,  710.,  580.,  720.,  880.,
       1160.,  860., 1110.,  680.,  830.,  550.,  110.,  310.,  120.,
        240.,  130.,  200.,   80.])

In [620]:
len(alpertc["Kaloriler"].unique()) #76 tane farklı kalori değeri bulunuyormuş.

76

In [621]:
alpertc["Kaloriler"].nunique() #Aynı işe yarar number of unique'den geliyor.

76

In [622]:
alpertc["Kaloriler"].value_counts() #Hangi sütunun hangi değerinden kaç tane olduğunu gösterir.

150.0     16
0.0       14
190.0     13
60.0      11
280.0     11
          ..
1150.0     1
610.0      1
790.0      1
750.0      1
520.0      1
Name: Kaloriler, Length: 76, dtype: int64

In [642]:
alpertc.info() #İle genel bilgi alabiliriz

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Item                  330 non-null    object
 1   Calories              328 non-null    float64
 2   Calories from
Fat     325 non-null    float64
 3   Total Fat
(g)         328 non-null    float64
 4   Saturated Fat
(g)     328 non-null    object
 5   Trans Fat
(g)         328 non-null    float64
 6   Cholesterol
(mg)      328 non-null    float64
 7   Sodium
(mg)          328 non-null    float64
 8   Carbs
(g)             328 non-null    float64
 9   Fiber
(g)             328 non-null    float64
 10  Sugars
(g)            328 non-null    float64
 11  Protein
(g)           328 non-null    float64
 12  Weight Watchers
Pnts  325 non-null    float64
dtypes: float64(11), object(2)
memory usage: 33.6+ KB